name: WolvenKit-Check-Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore WolvenKit.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release -p:Platform=x64 -m
